2024-04-07 19:27:34 INFO [32mpytest tests/frontend/test_e2e_build.py::test_create_build[chromium] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept: */*' \
-H 'Connection: keep-alive' \
-H 'Authorization: Basic OjYzNzg0NTUwMDI2Mjc5NTkzNjg=' \
2024-04-07 19:27:38 INFO [32mpytest tests/frontend/test_e2e_build.py::test_create_build[chromium][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept: application/json' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'X-TC-CSRF-Token: 433cc302-67c8-4099-b04c-065cbc1db754' \
-H 'Cookie: RecentLogin=; TCSESSIONID=0A0497C29F6B9BB6B4BBD7E3EA493754' \
-H 'Content-Length: 112' \
-H 'Authorization: Basic OjYzNzg0NTUwMDI2Mjc5NTkzNjg=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "skill", "id": "c6mCKhe8b43", "copyAllAssociatedSettings": true}' 

2024-04-07 19:27:38 INFO 	RESPONSE:
STATUS_CODE: [31m400[0m
DATA: [31mResponding with error, status code: 400 (Bad Request).
Details: jetbrains.buildServer.serverSide.DuplicateProjectNameException: Project with this name already exists: skill
Error occurred while processing this request.[0m
2024-04-07 19:27:38 INFO [32mpytest tests/frontend/test_e2e_build.py::test_create_build[chromium] (teardown)[0m
curl -X DELETE 'http://localhost:8111/app/rest/projects/id:c6mCKhe8b43' \
-H 'User-Agent: python-requests/2.31.0' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept: application/json' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'X-TC-CSRF-Token: 433cc302-67c8-4099-b04c-065cbc1db754' \
-H 'Cookie: TCSESSIONID=0A0497C29F6B9BB6B4BBD7E3EA493754' \
-H 'Content-Length: 0' \
-H 'Authorization: Basic OjYzNzg0NTUwMDI2Mjc5NTkzNjg=' \

2024-04-07 19:27:38 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:c6mCKhe8b43'. Project cannot be found by external id 'c6mCKhe8b43'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m